# Generated by Django 4.2.7 on 2023-12-12 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe_info', '0002_remove_recipegeninfo_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, unique=True)),
                ('name_lv', models.CharField(max_length=255, unique=True)),
                ('name_rus', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe_info.recipegeninfo')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_count', models.FloatField(null=True)),
                ('cooking_method', models.ManyToManyField(to='recipe_data.cookingmethod')),
                ('recipe_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe_data.recipedata')),
            ],
        ),
    ]
