# Generated by Django 4.2.7 on 2023-12-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='shop_unit',
        ),
        migrations.AddField(
            model_name='unit',
            name='type_shoping_only',
            field=models.BooleanField(null=True),
        ),
    ]
