# Generated by Django 4.2.7 on 2023-12-12 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_data', '0002_remove_unit_shop_unit_unit_type_shoping_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedingredient',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
