# Generated by Django 4.2.7 on 2023-11-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('servings', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
            ],
        ),
    ]
