# Generated by Django 4.2.7 on 2023-11-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('servings', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('cuisine', models.CharField(max_length=50, null=True)),
                ('meal', models.CharField(max_length=50, null=True)),
                ('food_category', models.CharField(max_length=50, null=True)),
                ('cooking_time', models.IntegerField(null=True)),
                ('equipment', models.TextField(null=True)),
                ('ingredient', models.TextField(null=True)),
                ('cooking_steps', models.TextField(null=True)),
                ('allergens', models.TextField(null=True)),
                ('ingredient_substitute', models.TextField(null=True)),
                ('nutritional_information', models.TextField(null=True)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('dietary_preference', models.CharField(max_length=50, null=True)),
                ('measurements', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
