# Generated by Django 4.2.7 on 2023-12-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_cookingstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, unique=True)),
                ('name_lv', models.CharField(max_length=255, unique=True)),
                ('name_rus', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_methods',
            field=models.ManyToManyField(to='catalog.cookingmethod'),
        ),
    ]
