# Generated by Django 4.2.7 on 2023-11-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingridient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('nosaukums', models.CharField(max_length=150)),
                ('calories', models.IntegerField(default=1)),
            ],
        ),
    ]
