# Generated by Django 4.2.7 on 2023-12-21 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=50, unique=True)),
                ('name_lv', models.CharField(max_length=50, unique=True)),
                ('name_rus', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, unique=True)),
                ('name_lv', models.CharField(max_length=255, unique=True)),
                ('name_rus', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CookingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, unique=True)),
                ('name_lv', models.CharField(max_length=255, unique=True)),
                ('name_rus', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, unique=True)),
                ('name_lv', models.CharField(max_length=255, unique=True)),
                ('name_rus', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.TextField()),
                ('name_lv', models.TextField(blank=True, max_length=3000, null=True)),
                ('name_rus', models.TextField(blank=True, max_length=3000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DietaryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, unique=True)),
                ('name_lv', models.CharField(max_length=255, unique=True)),
                ('name_rus', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, unique=True)),
                ('name_lv', models.CharField(max_length=255, unique=True)),
                ('name_rus', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, unique=True)),
                ('name_lv', models.CharField(max_length=255, unique=True)),
                ('name_rus', models.CharField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('allergen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.allergen')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, unique=True)),
                ('name_lv', models.CharField(max_length=255, unique=True)),
                ('name_rus', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, unique=True)),
                ('name_lv', models.CharField(max_length=255, unique=True)),
                ('name_rus', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, unique=True)),
                ('name_lv', models.CharField(max_length=255, unique=True)),
                ('name_rus', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooking_time', models.PositiveIntegerField()),
                ('servings', models.PositiveIntegerField()),
                ('cooking_methods', models.ManyToManyField(to='recipes.cookingmethod')),
                ('cuisine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.cuisine')),
                ('description', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.description')),
                ('dietary_preferences', models.ManyToManyField(to='recipes.dietarypreference')),
                ('equipment', models.ManyToManyField(to='recipes.equipment')),
                ('meal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.meal')),
                ('occasion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.occasion')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255)),
                ('name_lv', models.CharField(blank=True, max_length=255, null=True)),
                ('name_rus', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, unique=True)),
                ('name_lv', models.CharField(max_length=255, unique=True)),
                ('name_rus', models.CharField(max_length=255, unique=True)),
                ('type_shoping_valid', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.unit')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.title'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.ingredientcategory'),
        ),
        migrations.CreateModel(
            name='CookingStepInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField()),
                ('name_eng', models.TextField(blank=True, max_length=3000, null=True)),
                ('name_lv', models.TextField(blank=True, max_length=3000, null=True)),
                ('name_rus', models.TextField(blank=True, max_length=3000, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='CookingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField()),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('adjective_alt', models.ManyToManyField(blank=True, related_name='adjective_alt_set', to='recipes.adjective')),
                ('adjective_cm', models.ManyToManyField(blank=True, related_name='adjective_cm_set', to='recipes.adjective')),
                ('adjective_ri', models.ManyToManyField(blank=True, related_name='adjective_ri_set', to='recipes.adjective')),
                ('cooking_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.cookingmethod')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('recipe_ingredients', models.ManyToManyField(to='recipes.recipeingredient')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.unit')),
            ],
        ),
    ]
