# Generated by Django 4.2.7 on 2023-12-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjetive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=50, unique=True)),
                ('name_lv', models.CharField(max_length=50, unique=True)),
                ('name_rus', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
