# Generated by Django 4.2.7 on 2024-01-09 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_description_name_en_alter_description_name_lv_and_more'),
        ('recipes', '0003_alter_recipeingredient_quantity'),
    ]

    operations = [
    ]
