# Generated by Django 4.2.7 on 2024-02-28 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_merge_20240109_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookingstep',
            name='adjective_alt',
        ),
        migrations.RemoveField(
            model_name='cookingstep',
            name='adjective_cm',
        ),
        migrations.RemoveField(
            model_name='cookingstep',
            name='adjective_ri',
        ),
        migrations.RemoveField(
            model_name='cookingstep',
            name='cooking_method',
        ),
        migrations.RemoveField(
            model_name='cookingstep',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='cookingstep',
            name='recipe_ingredients',
        ),
        migrations.RemoveField(
            model_name='cookingstep',
            name='unit',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.DeleteModel(
            name='Adjective',
        ),
        migrations.DeleteModel(
            name='CookingStep',
        ),
    ]
