# Generated by Django 4.2.7 on 2024-03-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_cookingstep_adjective_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookingstepinstruction',
            name='name_en',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='cookingstepinstruction',
            name='name_lv',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='cookingstepinstruction',
            name='name_ru',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='cookingstepinstruction',
            name='step_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
