# Generated by Django 5.0.3 on 2024-03-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_cookingstepinstruction_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cuisine',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='occasion',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cuisines',
            field=models.ManyToManyField(to='recipes.cuisine'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meals',
            field=models.ManyToManyField(to='recipes.meal'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='occasions',
            field=models.ManyToManyField(to='recipes.occasion'),
        ),
    ]
