# Generated by Django 4.2.7 on 2023-12-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_cookingstep_quantity_alter_cookingstep_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookingstep',
            name='adjective',
        ),
        migrations.AddField(
            model_name='cookingstep',
            name='adjective_1',
            field=models.ManyToManyField(blank=True, related_name='adjective_1_set', to='recipes.adjective'),
        ),
        migrations.AddField(
            model_name='cookingstep',
            name='adjective_2',
            field=models.ManyToManyField(blank=True, related_name='adjective_2_set', to='recipes.adjective'),
        ),
        migrations.AddField(
            model_name='cookingstep',
            name='adjective_3',
            field=models.ManyToManyField(blank=True, related_name='adjective_3_set', to='recipes.adjective'),
        ),
        migrations.AddField(
            model_name='cookingstep',
            name='step_number',
            field=models.PositiveSmallIntegerField(default=3),
            preserve_default=False,
        ),
    ]
