# Generated by Django 5.0.3 on 2024-04-03 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_recipe_cuisine_remove_recipe_meal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 3, 11, 1, 38, 575899)),
        ),
        migrations.AddField(
            model_name='recipe',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 3, 11, 1, 38, 575899)),
        ),
    ]
