# Generated by Django 4.2.7 on 2023-12-14 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientcookingmethod',
            name='recipe',
        ),
        migrations.CreateModel(
            name='RecipeNextForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe_info.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientcookingmethod',
            name='recipe_next_form',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='recipe_info.recipenextform'),
            preserve_default=False,
        ),
    ]
