# Generated by Django 4.2.7 on 2023-12-14 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='title',
            name='recipe',
        ),
        migrations.AddField(
            model_name='geninfo',
            name='description',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe_info.description'),
        ),
        migrations.AddField(
            model_name='geninfo',
            name='title',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe_info.title'),
        ),
    ]
