# Generated by Django 4.2.7 on 2023-12-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipegeninfo',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='recipegeninfo',
            name='selected_ingredient',
            field=models.ManyToManyField(to='recipe_info.ingredient'),
        ),
    ]
