# Generated by Django 4.2.7 on 2023-12-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientCookingMethod',
            new_name='CookingSteps',
        ),
    ]
