# Generated by Django 4.2.7 on 2023-12-13 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipegeninfo',
            name='cooking_method',
        ),
    ]
