# Generated by Django 4.2.7 on 2023-12-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_info', '0002_remove_recipegeninfo_cooking_method'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeGenInfo',
            new_name='GenInfo',
        ),
    ]
