# Generated by Django 4.2.7 on 2023-12-13 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_info', '0002_description_title_alter_geninfo_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='name_lv',
        ),
        migrations.RemoveField(
            model_name='description',
            name='name_rus',
        ),
        migrations.RemoveField(
            model_name='title',
            name='name_lv',
        ),
        migrations.RemoveField(
            model_name='title',
            name='name_rus',
        ),
    ]
