# Generated by Django 4.2.7 on 2023-12-14 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_info', '0002_remove_ingredientcookingmethod_recipe_recipenextform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientcookingmethod',
            name='recipe_next_form',
        ),
        migrations.AddField(
            model_name='ingredientcookingmethod',
            name='recipe',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='recipe_info.recipe'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RecipeNextForm',
        ),
    ]
