# Generated by Django 4.2.7 on 2023-12-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_info', '0002_alter_cookingmethod_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookingmethod',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
