# Generated by Django 4.2.7 on 2023-12-12 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_info', '0002_remove_recipegeninfo_ingredient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, unique=True)),
                ('name_lv', models.CharField(max_length=255, unique=True)),
                ('name_rus', models.CharField(max_length=255, unique=True)),
                ('type_shoping_only', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField()),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe_info.ingredient')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe_info.recipegeninfo')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe_info.unit')),
            ],
        ),
    ]
