# Generated by Django 4.2.7 on 2023-12-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_info', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
