# Generated by Django 4.2.7 on 2023-12-13 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_info', '0003_remove_description_name_lv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geninfo',
            name='recipe',
        ),
        migrations.CreateModel(
            name='RecipeCookingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooking_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_info.cookingmethod')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_info.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_info.geninfo')),
            ],
        ),
    ]
