# Generated by Django 4.2.7 on 2023-12-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_info', '0003_remove_ingredientcookingmethod_recipe_next_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
