# Generated by Django 4.2.7 on 2023-12-13 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_info', '0003_rename_recipegeninfo_geninfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe_info.geninfo')),
            ],
        ),
    ]
