# Generated by Django 4.2.7 on 2023-12-13 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_info', '0004_remove_geninfo_recipe_recipecookingmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='geninfo',
            name='cooking_method',
            field=models.ManyToManyField(to='recipe_info.cookingmethod'),
        ),
        migrations.AlterField(
            model_name='recipecookingmethod',
            name='cooking_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe_info.cookingmethod'),
        ),
    ]
